**Assignment 4**

Group Members: - Group 2

Sam-Haendell Thosiac
Manuela Mouafo
Rodrigo Hache Caro

**Summary**

Questions: Which  breed types are found the most at which locations?

Outcomes: After cleaning and merging our data sets, we grouped the "breed type" by the location type. Specifcally, we looked at which breed is found the most in each city the data referenced.

The cities that we looked at were Travis TX, Cedar Park TX, Pflugerville (TX), Manor TX, Austin TX, Del Valle. The mix that was found the most at each city was, Austin TX and the Domestic Short Hair Mix and the amount was 7,411.

We looked at Austin TX more deeply to find the top two most mixes found at each city, In Manor TX, the most that was found was the Domestic Short Hair Mix (178) with Labrador retriver mix (97) as the second most found. In Pflugerville (TX), the most breed that was found was the Domestic Shorthair Mix at 174 with the second most, Pitbull at (84).In Del Valle, the most breed that was found was 165 with the second most found mix of Pitbull at (48). In Cedar Park TX, the most breed found was Domestic Shorthair Mix (21)the second most found breed was Pitbull(18). In Travis TX, the most found breed was the Domestic Short Hair Mix (491) and the seocnd most found breed was the Domestic Shorthair (456).

The company Austin Animal Shelter can use this information by making a specialized tab on their website. These tabs would be so customers can find the breed of the dog they want by going to the location that the breed was found the most. The tab would have the "most found breeds" within the state of Texas, then the specific tabs for "cities" and "breeds found" to allow for customers to find the breed they want. This also allows for people to see how many breeds were found at this location, just in case the breed they want are no longer there anymore.

R

In [ ]:
install.packages("janitor")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(dplyr)
library(tidyr)
library(dplyr)
library(janitor)
library(tidyverse)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

ERROR: Error in library(janitor): there is no package called ‘janitor’

Read The Data | R

In [ ]:
intakes <- read.csv("Austin_Animal_Center_Intakes.csv")
head(intakes, 5)

  Animal.ID Name     DateTime               MonthYear
1 A665644            10/21/2013 07:59:00 AM October 2013
2 A665739   *Alana   10/22/2013 11:11:00 AM October 2013
3 A665763            10/22/2013 03:10:00 PM October 2013
4 A379998   Disciple 10/23/2013 11:42:00 AM October 2013
5 A634503   Otter    10/01/2013 02:49:00 PM October 2013
  Found.Location                               Intake.Type     Intake.Condition
1 Austin (TX)                                  Stray           Sick
2 Austin (TX)                                  Stray           Normal
3 E Riverside Dr/Royal Crest Dr in Austin (TX) Stray           Normal
4 51St And Grover in Austin (TX)               Stray           Normal
5 Manor (TX)                                   Owner Surrender Normal
  Animal.Type Sex.upon.Intake Age.upon.Intake Breed
1 Cat         Intact Female   4 weeks         Domestic Shorthair Mix
2 Cat         Intact Female   1 month         Domestic Medium Hair Mix
3 Dog         Intact Male     4 months        Cairn Terrier Mix
4 Dog         Intact Male     10 years        Pit Bull
5 Dog         Spayed Female   2 years         Norfolk Terrier Mix
  Color
1 Calico
2 Black
3 Tan/White
4 Black
5 Tan

In [ ]:
outcomes <- read.csv("Austin_Animal_Center_Outcomes.csv")
head(outcomes, 5)

  Animal.ID Name  DateTime               MonthYear Date.of.Birth Outcome.Type
1 A794011   Chunk 05/08/2019 06:20:00 PM May 2019  05/02/2017    Rto-Adopt
2 A776359   Gizmo 07/18/2018 04:02:00 PM Jul 2018  07/12/2017    Adoption
3 A821648         08/16/2020 11:38:00 AM Aug 2020  08/16/2019    Euthanasia
4 A720371   Moose 02/13/2016 05:59:00 PM Feb 2016  10/08/2015    Adoption
5 A674754         03/18/2014 11:47:00 AM Mar 2014  03/12/2014    Transfer
  Outcome.Subtype Animal.Type Sex.upon.Outcome Age.upon.Outcome
1                 Cat         Neutered Male    2 years
2                 Dog         Neutered Male    1 year
3                 Other       Unknown          1 year
4                 Dog         Neutered Male    4 months
5 Partner         Cat         Intact Male      6 days
  Breed                              Color
1 Domestic Shorthair Mix             Brown Tabby/White
2 Chihuahua Shorthair Mix            White/Brown
3 Raccoon                            Gray
4 Anatol Shepherd/Labrador Retriever Buff
5 Domestic Shorthair Mix             Orange Tabby

In [ ]:
map <- read.csv("Austin_Animal_Center_Stray_Map.csv")
head(map, 5)

  Animal.ID Found.Location
1 A878853   5408 WESTMINSTER DRIVE\nAUSTIN 78723\n(30.30666, -97.68963)
2 A879012   5005 BUFFALO PASS\nAUSTIN 78745\n(30.22331, -97.79847)
3 A682044   JAKES HILL78660
4 A878939   EMERALD FOREST\nAUSTIN 78745
5 A879033   7301 SPICEWOOD SPRING RD78759\n(30.40673, -97.79031)
  At.AAC                     Intake.Date Type Looks.Like
1 Yes (come to the shelter)  04/18/2023  Dog  Pit Bull Mix
2 No (contact for more info) 04/20/2023  Cat  Domestic Shorthair
3 Yes (come to the shelter)  04/18/2023  Cat  Domestic Shorthair Mix
4 Yes (come to the shelter)  04/19/2023  Cat  Domestic Shorthair
5 Yes (come to the shelter)  04/20/2023  Dog  Pit Bull
  Color        Sex           Age
1 Blue/White   Intact Female 7 months
2 Orange Tabby Intact Female 6 weeks
3 Calico       Spayed Female 8 years
4 Brown Tabby  Intact Male   1 year
5 Blue/White   Intact Male   1 year
  Image.Link
1 http://www.petharbor.com/pet.asp?uaid=ASTN.A878853
2 http://www.petharbor.com/pet.asp?uaid=ASTN.A879012
3 http://www.petharbor.com/pet.asp?uaid=ASTN.A682044
4 http://www.petharbor.com/pet.asp?uaid=ASTN.A878939
5 http://www.petharbor.com/pet.asp?uaid=ASTN.A879033

Inspect the 3 Datasets

---

In [ ]:
names(intakes)
names(outcomes)
names(map)

 [1] "Animal.ID"        "Name"             "DateTime"         "MonthYear"
 [5] "Found.Location"   "Intake.Type"      "Intake.Condition" "Animal.Type"
 [9] "Sex.upon.Intake"  "Age.upon.Intake"  "Breed"            "Color"

 [1] "Animal.ID"        "Name"             "DateTime"         "MonthYear"
 [5] "Date.of.Birth"    "Outcome.Type"     "Outcome.Subtype"  "Animal.Type"
 [9] "Sex.upon.Outcome" "Age.upon.Outcome" "Breed"            "Color"

 [1] "Animal.ID"      "Found.Location" "At.AAC"         "Intake.Date"
 [5] "Type"           "Looks.Like"     "Color"          "Sex"
 [9] "Age"            "Image.Link"

Data Cleaning and Cleansing

In [ ]:
intakes  <- clean_names(intakes)
outcomes <- clean_names(outcomes)
map      <- clean_names(map)

Merging The Datasets

In [ ]:
#--Merge intakes + outcomes
merged <- intakes %>%
  left_join(outcomes, by = "animal_id")

#--Merge with stray map
merged_all <- merged %>%
  left_join(map, by = "animal_id")

Warning message in left_join(., outcomes, by = "animal_id"):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 15 of `x` matches multiple rows in `y`.
ℹ Row 20274 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

Cleaning the Dataset to take off Mostly NA Columns

In [ ]:
View(merged_all)

       animal_id name.x    date_time.x            month_year.x
1      A665644             10/21/2013 07:59:00 AM October 2013
2      A665739   *Alana    10/22/2013 11:11:00 AM October 2013
3      A665763             10/22/2013 03:10:00 PM October 2013
4      A379998   Disciple  10/23/2013 11:42:00 AM October 2013
5      A634503   Otter     10/01/2013 02:49:00 PM October 2013
6      A665496   Mikey     10/18/2013 06:07:00 PM October 2013
7      A665002             10/12/2013 11:45:00 AM October 2013
8      A664936   *Jester   10/11/2013 11:20:00 AM October 2013
9      A664235             10/01/2013 08:33:00 AM October 2013
10     A666101             10/26/2013 06:33:00 PM October 2013
11     A664830             10/09/2013 03:34:00 PM October 2013
12     A664262             10/01/2013 11:45:00 AM October 2013
13     A664887   *Gia      10/10/2013 01:48:00 PM October 2013
14     A665800   *Precious 10/23/2013 11:08:00 AM October 2013
15     A645345   Honey     10/01/2013 05:54:00 PM October 2013
16     A645345   Honey     10/01/2013 05:54:00 PM October 2013
17     A665817             10/23/2013 12:07:00 PM October 2013
18     A665706             10/21/2013 06:06:00 PM October 2013
19     A665615   Abby      10/20/2013 12:01:00 PM October 2013
20     A664468   *Jesse    10/03/2013 06:45:00 PM October 2013
21     A664770   *Frosty   10/08/2013 05:46:00 PM October 2013
22     A665923   Willow    10/24/2013 05:57:00 PM October 2013
23     A665923   Willow    10/24/2013 05:57:00 PM October 2013
24     A612451   Waffles   10/26/2013 01:56:00 PM October 2013
25     A663673   Frosty    10/02/2013 02:27:00 PM October 2013
26     A665398   Haven     10/17/2013 12:26:00 PM October 2013
27     A665856   Mocha     10/23/2013 04:11:00 PM October 2013
28     A665866   Rifle     10/23/2013 06:14:00 PM October 2013
29     A665426   Silka     10/17/2013 04:53:00 PM October 2013
30     A664742   Angel     10/08/2013 03:16:00 PM October 2013
⋮      ⋮         ⋮         ⋮                      ⋮
200378 A882467   *Mabel    06/05/2023 01:50:00 PM June 2023
200379 A882813   Verne     06/09/2023 11:27:00 AM June 2023
200380 A886628             08/08/2023 02:57:00 PM August 2023
200381 A883129   Mocha     06/13/2023 12:55:00 PM June 2023
200382 A885370   Egg Nog   07/18/2023 02:58:00 PM July 2023
200383 A886368   Josephine 08/04/2023 01:53:00 PM August 2023
200384 A885802   Neville   07/25/2023 04:43:00 PM July 2023
200385 A886620   Barbie    08/08/2023 01:14:00 PM August 2023
200386 A885797   Luna      07/25/2023 04:43:00 PM July 2023
200387 A882008   Pumpkin   05/30/2023 01:18:00 PM May 2023
200388 A886571             08/08/2023 08:29:00 AM August 2023
200389 A886569             08/08/2023 08:29:00 AM August 2023
200390 A886573             08/08/2023 08:29:00 AM August 2023
200391 A886572             08/08/2023 08:29:00 AM August 2023
200392 A886636             08/08/2023 03:30:00 PM August 2023
200393 A884257   Leo       06/30/2023 01:27:00 PM June 2023
200394 A886574             08/08/2023 08:29:00 AM August 2023
200395 A886388   Monkeyboy 08/04/2023 06:42:00 PM August 2023
200396 A884245   Bear      06/30/2023 12:32:00 PM June 2023
200397 A885910   Galaxy    07/27/2023 12:11:00 PM July 2023
200398 A886662   Mischief  08/09/2023 09:49:00 AM August 2023
200399 A886389   *Deepak   08/04/2023 08:06:00 PM August 2023
200400 A886649   886649    08/08/2023 06:52:00 PM August 2023
200401 A886665             08/09/2023 09:49:00 AM August 2023
200402 A886667             08/09/2023 09:49:00 AM August 2023
200403 A883852   *Percy    06/24/2023 03:00:00 PM June 2023
200404 A886631   *Franklin 08/08/2023 02:56:00 PM August 2023
200405 A882170   Osa       08/09/2023 12:02:00 PM August 2023
200406 A882170   Osa       08/09/2023 12:02:00 PM August 2023
200407 A886632   *Teddy    08/08/2023 02:56:00 PM August 2023
       found_location.x
1      Austin (TX)
2      Austin (TX)
3      E Riverside Dr/Royal Crest Dr in Austin (TX)
4      51St And Grover in Austin (TX)
5      Manor (TX)
6      12001 Metric Blvd in Austin (TX)
7      509 E Todd Lane in Austin (TX)
8      501 U.S. 183 in Austin (TX)
9      Abia in Austin (TX)
10     Payne in Austin (TX)
11     15043 Savannah Heights in Travis (TX)
12     4915 Yager Ln in Austin (TX)
13     1901 Onion Creek Pkwy in Austin (TX)
14     Austin (TX)
15     Austin (TX)
16     Austin (TX)
17     Austin (TX)
18     43 Rainey St in Austin (TX)
19     4708 Marblehead in Austin (TX)
20     23107 Fulkes Ln. in Austin (TX)
21     6808 Felipe Dr in Austin (TX)
22     Austin (TX)
23     Austin (TX)
24     111 E St Johns Ave in Austin (TX)
25     Travis (TX)
26     Austin (TX)
27     Montopolis/183 in Austin (TX)
28     2400 Wickersham in Austin (TX)
29     8224 Research Blvd #244 in Austin (TX)
30     Walsh Tarlton in Travis (TX)
⋮      ⋮
200378 1507 Darold Dr in Austin (TX)
200379 904 Fieldwood in Travis (TX)
200380 1020 Bird Creek in Austin (TX)
200381 Austin (TX)
200382 10705 Daryl Cove in Austin (TX)
200383 Rundberg Lane And Lamar Boulevard in Austin (TX)
200384 Fm 969 And Bantom Woods Road in Austin (TX)
200385 Austin (TX)
200386 Fm 969 And Bantom Woods Road in Austin (TX)
200387 12011 Yanez Drive in Travis (TX)
200388 1004 West Ave in Austin (TX)
200389 1004 West Ave in Austin (TX)
200390 1004 West Ave in Austin (TX)
200391 1004 West Ave in Austin (TX)
200392 Travis (TX)
200393 6907 Bitteroot Trl in Austin (TX)
200394 1004 West Ave in Austin (TX)
200395 2900 Sunridge Dr in Austin (TX)
200396 Austin (TX)
200397 Austin (TX)
200398 9000 Decker Ln Apt 246 in Travis (TX)
200399 Eva St And Johanna St in Austin (TX)
200400 Springdale in Austin (TX)
200401 9000 Decker Ln Apt 246 in Travis (TX)
200402 9000 Decker Ln Apt 246 in Travis (TX)
200403 Austin (TX)
200404 N Capital Of Texas Hwy And Plaza On The Lake in Austin (TX)
200405 Travis (TX)
200406 Travis (TX)
200407 N Capital Of Texas Hwy And Plaza On The Lake in Austin (TX)
       intake_type     intake_condition animal_type.x sex_upon_intake
1      Stray           Sick             Cat           Intact Female
2      Stray           Normal           Cat           Intact Female
3      Stray           Normal           Dog           Intact Male
4      Stray           Normal           Dog           Intact Male
5      Owner Surrender Normal           Dog           Spayed Female
6      Stray           Normal           Cat           Neutered Male
7      Stray           Normal           Dog           Intact Female
8      Stray           Normal           Cat           Intact Male
9      Stray           Normal           Cat           Unknown
10     Wildlife        Injured          Other         Unknown
11     Wildlife        Sick             Other         Unknown
12     Stray           Normal           Cat           Intact Male
13     Stray           Normal           Cat           Intact Female
14     Owner Surrender Normal           Cat           Intact Female
15     Owner Surrender Normal           Dog           Spayed Female
16     Owner Surrender Normal           Dog           Spayed Female
17     Stray           Normal           Dog           Intact Male
18     Wildlife        Normal           Other         Unknown
19     Stray           Normal           Dog           Spayed Female
20     Stray           Normal           Dog           Intact Male
21     Stray           Normal           Dog           Intact Female
22     Public Assist   Normal           Dog           Spayed Female
23     Public Assist   Normal           Dog           Spayed Female
24     Stray           Normal           Dog           Neutered Male
25     Owner Surrender Normal           Dog           Intact Male
26     Owner Surrender Normal           Cat           Intact Female
27     Stray           Normal           Dog           Intact Female
28     Stray           Normal           Dog           Intact Male
29     Stray           Normal           Cat           Intact Male
30     Stray           Normal           Dog           Intact Female
⋮      ⋮               ⋮                ⋮             ⋮
200378 Stray           Normal           Cat           Intact Female
200379 Stray           Normal           Cat           Intact Male
200380 Stray           Normal           Cat           Intact Female
200381 Owner Surrender Normal           Cat           Intact Female
200382 Stray           Normal           Cat           Intact Female
200383 Stray           Normal           Cat           Intact Female
200384 Stray           Normal           Cat           Intact Male
200385 Owner Surrender Normal           Cat           Spayed Female
200386 Stray           Normal           Cat           Intact Female
200387 Stray           Normal           Cat           Intact Female
200388 Stray           Neonatal         Cat           Intact Male
200389 Stray           Neonatal         Cat           Intact Male
200390 Stray           Neonatal         Cat           Intact Female
200391 Stray           Neonatal         Cat           Intact Female
200392 Owner Surrender Normal           Cat           Intact Male
200393 Stray           Normal           Cat           Intact Male
200394 Stray           Neonatal         Cat           Intact Male
200395 Stray           Normal           Cat           Intact Male
200396 Owner Surrender Normal           Dog           Intact Male
200397 Owner Surrender Sick             Cat           Intact Male
200398 Owner Surrender Normal           Cat           Intact Female
200399 Stray           Normal           Dog           Intact Male
200400 Stray           Normal           Cat           Intact Female
200401 Owner Surrender Normal           Cat           Intact Female
200402 Owner Surrender Normal           Cat           Intact Female
200403 Abandoned       Normal           Cat           Intact Male
200404 Stray           Normal           Cat           Intact Male
200405 Owner Surrender Injured          Dog           Spayed Female
200406 Owner Surrender Injured          Dog           Spayed Female
200407 Stray           Normal           Cat           Intact Male
       age_upon_intake ⋯ color.y            found_location.y at_aac intake_date
1      4 weeks         ⋯ Calico             NA               NA     NA
2      1 month         ⋯ Black              NA               NA     NA
3      4 months        ⋯ Tan/White          NA               NA     NA
4      10 years        ⋯ Black              NA               NA     NA
5      2 years         ⋯ Tan                NA               NA     NA
6      3 years         ⋯ Brown Tiger        NA               NA     NA
7      1 week          ⋯ Sable/White        NA               NA     NA
8      1 month         ⋯ Brown Tabby        NA               NA     NA
9      1 week          ⋯ Orange/White       NA               NA     NA
10     0 years         ⋯ Gray/Brown         NA               NA     NA
11     1 year          ⋯ Brown/Black        NA               NA     NA
12     1 weeks         ⋯ Orange Tabby       NA               NA     NA
13     1 month         ⋯ Black              NA               NA     NA
14     3 months        ⋯ Tortie             NA               NA     NA
15     1 year          ⋯ Brown/White        NA               NA     NA
16     1 year          ⋯ Brown/White        NA               NA     NA
17     2 months        ⋯ White/Chocolate    NA               NA     NA
18     1 year          ⋯ Brown              NA               NA     NA
19     8 years         ⋯ Chocolate/White    NA               NA     NA
20     1 year          ⋯ Tan/White          NA               NA     NA
21     3 months        ⋯ Blue Merle/Cream   NA               NA     NA
22     1 year          ⋯ Red                NA               NA     NA
23     1 year          ⋯ Red                NA               NA     NA
24     2 years         ⋯ Tan                NA               NA     NA
25     4 years         ⋯ White              NA               NA     NA
26     1 month         ⋯ White/Blue         NA               NA     NA
27     9 months        ⋯ Chocolate          NA               NA     NA
28     8 years         ⋯ Tricolor           NA               NA     NA
29     1 month         ⋯ Black              NA               NA     NA
30     4 years         ⋯ Black/White        NA               NA     NA
⋮      ⋮               ⋱ ⋮                  ⋮                ⋮      ⋮
200378 1 month         ⋯ Blue Tabby         NA               NA     NA
200379 1 month         ⋯ Brown Tabby/White  NA               NA     NA
200380 4 months        ⋯ Agouti/Brown Tabby NA               NA     NA
200381 2 months        ⋯ Brown Tabby        NA               NA     NA
200382 1 month         ⋯ Calico/White       NA               NA     NA
200383 3 months        ⋯ Brown Tabby/White  NA               NA     NA
200384 2 months        ⋯ Orange Tabby       NA               NA     NA
200385 8 months        ⋯ Black/White        NA               NA     NA
200386 2 months        ⋯ Calico             NA               NA     NA
200387 1 year          ⋯ Brown Tabby        NA               NA     NA
200388 2 weeks         ⋯ Seal Point         NA               NA     NA
200389 2 weeks         ⋯ Seal Point         NA               NA     NA
200390 2 weeks         ⋯ Brown Tabby        NA               NA     NA
200391 2 weeks         ⋯ Brown Tabby        NA               NA     NA
200392 5 months        ⋯ Black/White        NA               NA     NA
200393 1 month         ⋯ Black/White        NA               NA     NA
200394 2 weeks         ⋯ Brown Tabby        NA               NA     NA
200395 1 year          ⋯ Blue Tabby         NA               NA     NA
200396 3 years         ⋯ NA                 NA               NA     NA
200397 5 months        ⋯ Blue/White         NA               NA     NA
200398 2 years         ⋯ Brown Tabby/White  NA               NA     NA
200399 2 years         ⋯ NA                 NA               NA     NA
200400 2 weeks         ⋯ Brown Tabby        NA               NA     NA
200401 3 months        ⋯ Black/White        NA               NA     NA
200402 3 months        ⋯ Brown Tabby/White  NA               NA     NA
200403 10 months       ⋯ Brown Tabby        NA               NA     NA
200404 1 month         ⋯ Lynx Point         NA               NA     NA
200405 9 months        ⋯ Black/White        NA               NA     NA
200406 9 months        ⋯ Black/White        NA               NA     NA
200407 1 month         ⋯ White/Silver       NA               NA     NA
       type looks_like color sex age image_link
1      NA   NA         NA    NA  NA  NA
2      NA   NA         NA    NA  NA  NA
3      NA   NA         NA    NA  NA  NA
4      NA   NA         NA    NA  NA  NA
5      NA   NA         NA    NA  NA  NA
6      NA   NA         NA    NA  NA  NA
7      NA   NA         NA    NA  NA  NA
8      NA   NA         NA    NA  NA  NA
9      NA   NA         NA    NA  NA  NA
10     NA   NA         NA    NA  NA  NA
11     NA   NA         NA    NA  NA  NA
12     NA   NA         NA    NA  NA  NA
13     NA   NA         NA    NA  NA  NA
14     NA   NA         NA    NA  NA  NA
15     NA   NA         NA    NA  NA  NA
16     NA   NA         NA    NA  NA  NA
17     NA   NA         NA    NA  NA  NA
18     NA   NA         NA    NA  NA  NA
19     NA   NA         NA    NA  NA  NA
20     NA   NA         NA    NA  NA  NA
21     NA   NA         NA    NA  NA  NA
22     NA   NA         NA    NA  NA  NA
23     NA   NA         NA    NA  NA  NA
24     NA   NA         NA    NA  NA  NA
25     NA   NA         NA    NA  NA  NA
26     NA   NA         NA    NA  NA  NA
27     NA   NA         NA    NA  NA  NA
28     NA   NA         NA    NA  NA  NA
29     NA   NA         NA    NA  NA  NA
30     NA   NA         NA    NA  NA  NA
⋮      ⋮    ⋮          ⋮     ⋮   ⋮   ⋮
200378 NA   NA         NA    NA  NA  NA
200379 NA   NA         NA    NA  NA  NA
200380 NA   NA         NA    NA  NA  NA
200381 NA   NA         NA    NA  NA  NA
200382 NA   NA         NA    NA  NA  NA
200383 NA   NA         NA    NA  NA  NA
200384 NA   NA         NA    NA  NA  NA
200385 NA   NA         NA    NA  NA  NA
200386 NA   NA         NA    NA  NA  NA
200387 NA   NA         NA    NA  NA  NA
200388 NA   NA         NA    NA  NA  NA
200389 NA   NA         NA    NA  NA  NA
200390 NA   NA         NA    NA  NA  NA
200391 NA   NA         NA    NA  NA  NA
200392 NA   NA         NA    NA  NA  NA
200393 NA   NA         NA    NA  NA  NA
200394 NA   NA         NA    NA  NA  NA
200395 NA   NA         NA    NA  NA  NA
200396 NA   NA         NA    NA  NA  NA
200397 NA   NA         NA    NA  NA  NA
200398 NA   NA         NA    NA  NA  NA
200399 NA   NA         NA    NA  NA  NA
200400 NA   NA         NA    NA  NA  NA
200401 NA   NA         NA    NA  NA  NA
200402 NA   NA         NA    NA  NA  NA
200403 NA   NA         NA    NA  NA  NA
200404 NA   NA         NA    NA  NA  NA
200405 NA   NA         NA    NA  NA  NA
200406 NA   NA         NA    NA  NA  NA
200407 NA   NA         NA    NA  NA  NA

Clean by Empty Columns

In [ ]:
merged_clean <- merged_all %>%
  select(where(~ mean(is.na(.)) < 0.5))
View(merged_clean)

       animal_id name.x    date_time.x            month_year.x
1      A665644             10/21/2013 07:59:00 AM October 2013
2      A665739   *Alana    10/22/2013 11:11:00 AM October 2013
3      A665763             10/22/2013 03:10:00 PM October 2013
4      A379998   Disciple  10/23/2013 11:42:00 AM October 2013
5      A634503   Otter     10/01/2013 02:49:00 PM October 2013
6      A665496   Mikey     10/18/2013 06:07:00 PM October 2013
7      A665002             10/12/2013 11:45:00 AM October 2013
8      A664936   *Jester   10/11/2013 11:20:00 AM October 2013
9      A664235             10/01/2013 08:33:00 AM October 2013
10     A666101             10/26/2013 06:33:00 PM October 2013
11     A664830             10/09/2013 03:34:00 PM October 2013
12     A664262             10/01/2013 11:45:00 AM October 2013
13     A664887   *Gia      10/10/2013 01:48:00 PM October 2013
14     A665800   *Precious 10/23/2013 11:08:00 AM October 2013
15     A645345   Honey     10/01/2013 05:54:00 PM October 2013
16     A645345   Honey     10/01/2013 05:54:00 PM October 2013
17     A665817             10/23/2013 12:07:00 PM October 2013
18     A665706             10/21/2013 06:06:00 PM October 2013
19     A665615   Abby      10/20/2013 12:01:00 PM October 2013
20     A664468   *Jesse    10/03/2013 06:45:00 PM October 2013
21     A664770   *Frosty   10/08/2013 05:46:00 PM October 2013
22     A665923   Willow    10/24/2013 05:57:00 PM October 2013
23     A665923   Willow    10/24/2013 05:57:00 PM October 2013
24     A612451   Waffles   10/26/2013 01:56:00 PM October 2013
25     A663673   Frosty    10/02/2013 02:27:00 PM October 2013
26     A665398   Haven     10/17/2013 12:26:00 PM October 2013
27     A665856   Mocha     10/23/2013 04:11:00 PM October 2013
28     A665866   Rifle     10/23/2013 06:14:00 PM October 2013
29     A665426   Silka     10/17/2013 04:53:00 PM October 2013
30     A664742   Angel     10/08/2013 03:16:00 PM October 2013
⋮      ⋮         ⋮         ⋮                      ⋮
200378 A882467   *Mabel    06/05/2023 01:50:00 PM June 2023
200379 A882813   Verne     06/09/2023 11:27:00 AM June 2023
200380 A886628             08/08/2023 02:57:00 PM August 2023
200381 A883129   Mocha     06/13/2023 12:55:00 PM June 2023
200382 A885370   Egg Nog   07/18/2023 02:58:00 PM July 2023
200383 A886368   Josephine 08/04/2023 01:53:00 PM August 2023
200384 A885802   Neville   07/25/2023 04:43:00 PM July 2023
200385 A886620   Barbie    08/08/2023 01:14:00 PM August 2023
200386 A885797   Luna      07/25/2023 04:43:00 PM July 2023
200387 A882008   Pumpkin   05/30/2023 01:18:00 PM May 2023
200388 A886571             08/08/2023 08:29:00 AM August 2023
200389 A886569             08/08/2023 08:29:00 AM August 2023
200390 A886573             08/08/2023 08:29:00 AM August 2023
200391 A886572             08/08/2023 08:29:00 AM August 2023
200392 A886636             08/08/2023 03:30:00 PM August 2023
200393 A884257   Leo       06/30/2023 01:27:00 PM June 2023
200394 A886574             08/08/2023 08:29:00 AM August 2023
200395 A886388   Monkeyboy 08/04/2023 06:42:00 PM August 2023
200396 A884245   Bear      06/30/2023 12:32:00 PM June 2023
200397 A885910   Galaxy    07/27/2023 12:11:00 PM July 2023
200398 A886662   Mischief  08/09/2023 09:49:00 AM August 2023
200399 A886389   *Deepak   08/04/2023 08:06:00 PM August 2023
200400 A886649   886649    08/08/2023 06:52:00 PM August 2023
200401 A886665             08/09/2023 09:49:00 AM August 2023
200402 A886667             08/09/2023 09:49:00 AM August 2023
200403 A883852   *Percy    06/24/2023 03:00:00 PM June 2023
200404 A886631   *Franklin 08/08/2023 02:56:00 PM August 2023
200405 A882170   Osa       08/09/2023 12:02:00 PM August 2023
200406 A882170   Osa       08/09/2023 12:02:00 PM August 2023
200407 A886632   *Teddy    08/08/2023 02:56:00 PM August 2023
       found_location.x
1      Austin (TX)
2      Austin (TX)
3      E Riverside Dr/Royal Crest Dr in Austin (TX)
4      51St And Grover in Austin (TX)
5      Manor (TX)
6      12001 Metric Blvd in Austin (TX)
7      509 E Todd Lane in Austin (TX)
8      501 U.S. 183 in Austin (TX)
9      Abia in Austin (TX)
10     Payne in Austin (TX)
11     15043 Savannah Heights in Travis (TX)
12     4915 Yager Ln in Austin (TX)
13     1901 Onion Creek Pkwy in Austin (TX)
14     Austin (TX)
15     Austin (TX)
16     Austin (TX)
17     Austin (TX)
18     43 Rainey St in Austin (TX)
19     4708 Marblehead in Austin (TX)
20     23107 Fulkes Ln. in Austin (TX)
21     6808 Felipe Dr in Austin (TX)
22     Austin (TX)
23     Austin (TX)
24     111 E St Johns Ave in Austin (TX)
25     Travis (TX)
26     Austin (TX)
27     Montopolis/183 in Austin (TX)
28     2400 Wickersham in Austin (TX)
29     8224 Research Blvd #244 in Austin (TX)
30     Walsh Tarlton in Travis (TX)
⋮      ⋮
200378 1507 Darold Dr in Austin (TX)
200379 904 Fieldwood in Travis (TX)
200380 1020 Bird Creek in Austin (TX)
200381 Austin (TX)
200382 10705 Daryl Cove in Austin (TX)
200383 Rundberg Lane And Lamar Boulevard in Austin (TX)
200384 Fm 969 And Bantom Woods Road in Austin (TX)
200385 Austin (TX)
200386 Fm 969 And Bantom Woods Road in Austin (TX)
200387 12011 Yanez Drive in Travis (TX)
200388 1004 West Ave in Austin (TX)
200389 1004 West Ave in Austin (TX)
200390 1004 West Ave in Austin (TX)
200391 1004 West Ave in Austin (TX)
200392 Travis (TX)
200393 6907 Bitteroot Trl in Austin (TX)
200394 1004 West Ave in Austin (TX)
200395 2900 Sunridge Dr in Austin (TX)
200396 Austin (TX)
200397 Austin (TX)
200398 9000 Decker Ln Apt 246 in Travis (TX)
200399 Eva St And Johanna St in Austin (TX)
200400 Springdale in Austin (TX)
200401 9000 Decker Ln Apt 246 in Travis (TX)
200402 9000 Decker Ln Apt 246 in Travis (TX)
200403 Austin (TX)
200404 N Capital Of Texas Hwy And Plaza On The Lake in Austin (TX)
200405 Travis (TX)
200406 Travis (TX)
200407 N Capital Of Texas Hwy And Plaza On The Lake in Austin (TX)
       intake_type     intake_condition animal_type.x sex_upon_intake
1      Stray           Sick             Cat           Intact Female
2      Stray           Normal           Cat           Intact Female
3      Stray           Normal           Dog           Intact Male
4      Stray           Normal           Dog           Intact Male
5      Owner Surrender Normal           Dog           Spayed Female
6      Stray           Normal           Cat           Neutered Male
7      Stray           Normal           Dog           Intact Female
8      Stray           Normal           Cat           Intact Male
9      Stray           Normal           Cat           Unknown
10     Wildlife        Injured          Other         Unknown
11     Wildlife        Sick             Other         Unknown
12     Stray           Normal           Cat           Intact Male
13     Stray           Normal           Cat           Intact Female
14     Owner Surrender Normal           Cat           Intact Female
15     Owner Surrender Normal           Dog           Spayed Female
16     Owner Surrender Normal           Dog           Spayed Female
17     Stray           Normal           Dog           Intact Male
18     Wildlife        Normal           Other         Unknown
19     Stray           Normal           Dog           Spayed Female
20     Stray           Normal           Dog           Intact Male
21     Stray           Normal           Dog           Intact Female
22     Public Assist   Normal           Dog           Spayed Female
23     Public Assist   Normal           Dog           Spayed Female
24     Stray           Normal           Dog           Neutered Male
25     Owner Surrender Normal           Dog           Intact Male
26     Owner Surrender Normal           Cat           Intact Female
27     Stray           Normal           Dog           Intact Female
28     Stray           Normal           Dog           Intact Male
29     Stray           Normal           Cat           Intact Male
30     Stray           Normal           Dog           Intact Female
⋮      ⋮               ⋮                ⋮             ⋮
200378 Stray           Normal           Cat           Intact Female
200379 Stray           Normal           Cat           Intact Male
200380 Stray           Normal           Cat           Intact Female
200381 Owner Surrender Normal           Cat           Intact Female
200382 Stray           Normal           Cat           Intact Female
200383 Stray           Normal           Cat           Intact Female
200384 Stray           Normal           Cat           Intact Male
200385 Owner Surrender Normal           Cat           Spayed Female
200386 Stray           Normal           Cat           Intact Female
200387 Stray           Normal           Cat           Intact Female
200388 Stray           Neonatal         Cat           Intact Male
200389 Stray           Neonatal         Cat           Intact Male
200390 Stray           Neonatal         Cat           Intact Female
200391 Stray           Neonatal         Cat           Intact Female
200392 Owner Surrender Normal           Cat           Intact Male
200393 Stray           Normal           Cat           Intact Male
200394 Stray           Neonatal         Cat           Intact Male
200395 Stray           Normal           Cat           Intact Male
200396 Owner Surrender Normal           Dog           Intact Male
200397 Owner Surrender Sick             Cat           Intact Male
200398 Owner Surrender Normal           Cat           Intact Female
200399 Stray           Normal           Dog           Intact Male
200400 Stray           Normal           Cat           Intact Female
200401 Owner Surrender Normal           Cat           Intact Female
200402 Owner Surrender Normal           Cat           Intact Female
200403 Abandoned       Normal           Cat           Intact Male
200404 Stray           Normal           Cat           Intact Male
200405 Owner Surrender Injured          Dog           Spayed Female
200406 Owner Surrender Injured          Dog           Spayed Female
200407 Stray           Normal           Cat           Intact Male
       age_upon_intake ⋯ date_time.y            month_year.y date_of_birth
1      4 weeks         ⋯ 10/21/2013 11:39:00 AM Oct 2013     09/21/2013
2      1 month         ⋯ 12/20/2013 05:36:00 PM Dec 2013     09/16/2013
3      4 months        ⋯ 10/26/2013 06:32:00 PM Oct 2013     06/22/2013
4      10 years        ⋯ 10/25/2013 12:53:00 PM Oct 2013     02/21/2003
5      2 years         ⋯ 10/02/2013 12:40:00 PM Oct 2013     08/11/2011
6      3 years         ⋯ 10/22/2013 05:54:00 PM Oct 2013     04/18/2010
7      1 week          ⋯ 10/15/2013 02:33:00 PM Oct 2013     10/05/2013
8      1 month         ⋯ 12/18/2013 06:18:00 PM Dec 2013     08/18/2013
9      1 week          ⋯ 10/01/2013 10:39:00 AM Oct 2013     09/24/2013
10     0 years         ⋯ 10/26/2013 06:45:00 PM Oct 2013     10/26/2013
11     1 year          ⋯ 10/09/2013 03:59:00 PM Oct 2013     10/09/2012
12     1 weeks         ⋯ 10/01/2013 12:59:00 PM Oct 2013     09/22/2013
13     1 month         ⋯ 11/10/2013 04:56:00 PM Nov 2013     08/10/2013
14     3 months        ⋯ 11/10/2013 06:50:00 PM Nov 2013     07/23/2013
15     1 year          ⋯ 10/20/2013 04:29:00 PM Oct 2013     01/06/2012
16     1 year          ⋯ 05/12/2018 06:27:00 PM May 2018     01/06/2012
17     2 months        ⋯ 10/27/2013 04:30:00 PM Oct 2013     08/08/2013
18     1 year          ⋯ 10/21/2013 06:50:00 PM Oct 2013     10/21/2012
19     8 years         ⋯ 10/20/2013 03:10:00 PM Oct 2013     05/20/2005
20     1 year          ⋯ 03/04/2014 12:17:00 PM Mar 2014     04/03/2012
21     3 months        ⋯ 10/13/2013 07:06:00 PM Oct 2013     06/23/2013
22     1 year          ⋯ 07/23/2016 03:41:00 PM Jul 2016     04/24/2012
23     1 year          ⋯ 11/04/2013 03:00:00 PM Nov 2013     04/24/2012
24     2 years         ⋯ 10/27/2013 12:29:00 PM Oct 2013     08/01/2011
25     4 years         ⋯ 11/15/2013 06:13:00 PM Nov 2013     10/10/2008
26     1 month         ⋯ 11/10/2013 04:45:00 PM Nov 2013     08/19/2013
27     9 months        ⋯ 10/24/2013 04:54:00 PM Oct 2013     12/23/2012
28     8 years         ⋯ 10/28/2013 11:13:00 AM Oct 2013     10/23/2005
29     1 month         ⋯ 11/16/2013 05:09:00 PM Nov 2013     08/26/2013
30     4 years         ⋯ 10/11/2013 06:08:00 PM Oct 2013     10/08/2009
⋮      ⋮               ⋱ ⋮                      ⋮            ⋮
200378 1 month         ⋯ 08/12/2023 12:48:00 PM Aug 2023     04/27/2023
200379 1 month         ⋯ 08/08/2023 04:38:00 PM Aug 2023     04/26/2023
200380 4 months        ⋯ 09/07/2023 05:05:00 PM Sep 2023     03/24/2023
200381 2 months        ⋯ 08/08/2023 04:24:00 PM Aug 2023     04/06/2023
200382 1 month         ⋯ 08/08/2023 04:32:00 PM Aug 2023     05/28/2023
200383 3 months        ⋯ 08/22/2023 05:05:00 PM Aug 2023     05/04/2023
200384 2 months        ⋯ 08/08/2023 05:27:00 PM Aug 2023     05/22/2023
200385 8 months        ⋯ 08/13/2023 04:28:00 PM Aug 2023     11/08/2022
200386 2 months        ⋯ 08/08/2023 05:27:00 PM Aug 2023     05/22/2023
200387 1 year          ⋯ 08/08/2023 04:57:00 PM Aug 2023     05/30/2022
200388 2 weeks         ⋯ 08/08/2023 07:17:00 PM Aug 2023     07/20/2023
200389 2 weeks         ⋯ 08/08/2023 07:17:00 PM Aug 2023     07/20/2023
200390 2 weeks         ⋯ 08/08/2023 07:18:00 PM Aug 2023     07/20/2023
200391 2 weeks         ⋯ 08/08/2023 07:17:00 PM Aug 2023     07/20/2023
200392 5 months        ⋯ 08/16/2023 06:15:00 PM Aug 2023     03/08/2023
200393 1 month         ⋯ 08/08/2023 06:10:00 PM Aug 2023     04/30/2023
200394 2 weeks         ⋯ 08/08/2023 07:18:00 PM Aug 2023     07/20/2023
200395 1 year          ⋯ 08/16/2023 05:26:00 PM Aug 2023     07/21/2022
200396 3 years         ⋯ NA                     NA           NA
200397 5 months        ⋯ 08/26/2023 02:36:00 PM Aug 2023     02/20/2023
200398 2 years         ⋯ 08/22/2023 04:38:00 PM Aug 2023     08/09/2021
200399 2 years         ⋯ NA                     NA           NA
200400 2 weeks         ⋯ 08/09/2023 12:49:00 PM Aug 2023     07/24/2023
200401 3 months        ⋯ 08/17/2023 05:10:00 PM Aug 2023     05/09/2023
200402 3 months        ⋯ 08/17/2023 05:09:00 PM Aug 2023     05/09/2023
200403 10 months       ⋯ 08/26/2023 05:49:00 PM Aug 2023     08/09/2022
200404 1 month         ⋯ 09/13/2023 10:02:00 AM Sep 2023     06/28/2023
200405 9 months        ⋯ 08/15/2023 02:18:00 PM Aug 2023     11/01/2022
200406 9 months        ⋯ 07/06/2023 04:55:00 PM Jul 2023     11/01/2022
200407 1 month         ⋯ 09/11/2023 04:09:00 PM Sep 2023     06/28/2023
       outcome_type    outcome_subtype animal_type.y sex_upon_outcome
1      Transfer        Partner         Cat           Intact Female
2      Adoption        Foster          Cat           Spayed Female
3      Adoption                        Dog           Neutered Male
4      Return to Owner                 Dog           Intact Male
5      Adoption                        Dog           Spayed Female
6      Adoption                        Cat           Neutered Male
7      Transfer        Partner         Dog           Intact Female
8      Adoption                        Cat           Neutered Male
9      Transfer        Partner         Cat           Unknown
10     Euthanasia                      Other         Unknown
11     Euthanasia      Suffering       Other         Unknown
12     Transfer        Partner         Cat           Intact Male
13     Adoption                        Cat           Spayed Female
14     Transfer        Partner         Cat           Spayed Female
15     Transfer        Partner         Dog           Spayed Female
16     Return to Owner                 Dog           Spayed Female
17     Transfer        Partner         Dog           Neutered Male
18     Disposal                        Other         Unknown
19     Return to Owner                 Dog           Spayed Female
20     Adoption        Foster          Dog           Neutered Male
21     Adoption                        Dog           Spayed Female
22     Return to Owner                 Dog           Spayed Female
23     Return to Owner                 Dog           Spayed Female
24     Return to Owner                 Dog           Neutered Male
25     Transfer        Partner         Dog           Neutered Male
26     Adoption                        Cat           Spayed Female
27     Transfer        Partner         Dog           Intact Female
28     Return to Owner                 Dog           Neutered Male
29     Adoption                        Cat           Neutered Male
30     Return to Owner                 Dog           Spayed Female
⋮      ⋮               ⋮               ⋮             ⋮
200378 Adoption        Foster          Cat           Spayed Female
200379 Adoption                        Cat           Neutered Male
200380 Adoption                        Cat           Spayed Female
200381 Adoption                        Cat           Spayed Female
200382 Adoption                        Cat           Spayed Female
200383 Adoption        Foster          Cat           Spayed Female
200384 Adoption                        Cat           Neutered Male
200385 Adoption                        Cat           Spayed Female
200386 Adoption                        Cat           Spayed Female
200387 Adoption                        Cat           Spayed Female
200388 Transfer        Partner         Cat           Intact Male
200389 Transfer        Partner         Cat           Intact Male
200390 Transfer        Partner         Cat           Intact Female
200391 Transfer        Partner         Cat           Intact Female
200392 Adoption                        Cat           Neutered Male
200393 Adoption                        Cat           Neutered Male
200394 Transfer        Partner         Cat           Intact Male
200395 Adoption                        Cat           Neutered Male
200396 NA              NA              NA            NA
200397 Adoption        Foster          Cat           Neutered Male
200398 Adoption                        Cat           Spayed Female
200399 NA              NA              NA            NA
200400 Transfer        Partner         Cat           Intact Female
200401 Adoption        Foster          Cat           Spayed Female
200402 Adoption        Foster          Cat           Spayed Female
200403 Adoption                        Cat           Neutered Male
200404 Adoption        Foster          Cat           Neutered Male
200405 Transfer        Partner         Dog           Spayed Female
200406 Rto-Adopt                       Dog           Spayed Female
200407 Adoption        Foster          Cat           Neutered Male
       age_upon_outcome breed.y                            color.y
1      4 weeks          Domestic Shorthair Mix             Calico
2      3 months         Domestic Medium Hair Mix           Black
3      4 months         Cairn Terrier Mix                  Tan/White
4      10 years         Pit Bull                           Black
5      2 years          Norfolk Terrier Mix                Tan
6      3 years          Bengal                             Brown Tiger
7      1 weeks          Australian Cattle Dog Mix          Sable/White
8      4 months         Domestic Medium Hair Mix           Brown Tabby
9      1 week           Domestic Shorthair Mix             Orange/White
10     0 years          Squirrel Mix                       Gray/Brown
11     1 year           Raccoon Mix                        Brown/Black
12     1 weeks          Domestic Shorthair Mix             Orange Tabby
13     3 months         Domestic Shorthair Mix             Black
14     3 months         Domestic Shorthair Mix             Tortie
15     1 year           Pit Bull Mix                       Brown/White
16     6 years          Pit Bull Mix                       Brown/White
17     2 months         Chihuahua Shorthair Mix            White/Chocolate
18     1 year           Bat Mix                            Brown
19     8 years          Border Collie/Labrador Retriever   Chocolate/White

Clean The Merge By Empty Rows | Final Cleanse

In [ ]:
merged_noempty <- merged_clean %>%
  filter(!if_all(everything(), is.na))
View(merged_noempty)

       animal_id name.x    date_time.x            month_year.x
1      A665644             10/21/2013 07:59:00 AM October 2013
2      A665739   *Alana    10/22/2013 11:11:00 AM October 2013
3      A665763             10/22/2013 03:10:00 PM October 2013
4      A379998   Disciple  10/23/2013 11:42:00 AM October 2013
5      A634503   Otter     10/01/2013 02:49:00 PM October 2013
6      A665496   Mikey     10/18/2013 06:07:00 PM October 2013
7      A665002             10/12/2013 11:45:00 AM October 2013
8      A664936   *Jester   10/11/2013 11:20:00 AM October 2013
9      A664235             10/01/2013 08:33:00 AM October 2013
10     A666101             10/26/2013 06:33:00 PM October 2013
11     A664830             10/09/2013 03:34:00 PM October 2013
12     A664262             10/01/2013 11:45:00 AM October 2013
13     A664887   *Gia      10/10/2013 01:48:00 PM October 2013
14     A665800   *Precious 10/23/2013 11:08:00 AM October 2013
15     A645345   Honey     10/01/2013 05:54:00 PM October 2013
16     A645345   Honey     10/01/2013 05:54:00 PM October 2013
17     A665817             10/23/2013 12:07:00 PM October 2013
18     A665706             10/21/2013 06:06:00 PM October 2013
19     A665615   Abby      10/20/2013 12:01:00 PM October 2013
20     A664468   *Jesse    10/03/2013 06:45:00 PM October 2013
21     A664770   *Frosty   10/08/2013 05:46:00 PM October 2013
22     A665923   Willow    10/24/2013 05:57:00 PM October 2013
23     A665923   Willow    10/24/2013 05:57:00 PM October 2013
24     A612451   Waffles   10/26/2013 01:56:00 PM October 2013
25     A663673   Frosty    10/02/2013 02:27:00 PM October 2013
26     A665398   Haven     10/17/2013 12:26:00 PM October 2013
27     A665856   Mocha     10/23/2013 04:11:00 PM October 2013
28     A665866   Rifle     10/23/2013 06:14:00 PM October 2013
29     A665426   Silka     10/17/2013 04:53:00 PM October 2013
30     A664742   Angel     10/08/2013 03:16:00 PM October 2013
⋮      ⋮         ⋮         ⋮                      ⋮
200378 A882467   *Mabel    06/05/2023 01:50:00 PM June 2023
200379 A882813   Verne     06/09/2023 11:27:00 AM June 2023
200380 A886628             08/08/2023 02:57:00 PM August 2023
200381 A883129   Mocha     06/13/2023 12:55:00 PM June 2023
200382 A885370   Egg Nog   07/18/2023 02:58:00 PM July 2023
200383 A886368   Josephine 08/04/2023 01:53:00 PM August 2023
200384 A885802   Neville   07/25/2023 04:43:00 PM July 2023
200385 A886620   Barbie    08/08/2023 01:14:00 PM August 2023
200386 A885797   Luna      07/25/2023 04:43:00 PM July 2023
200387 A882008   Pumpkin   05/30/2023 01:18:00 PM May 2023
200388 A886571             08/08/2023 08:29:00 AM August 2023
200389 A886569             08/08/2023 08:29:00 AM August 2023
200390 A886573             08/08/2023 08:29:00 AM August 2023
200391 A886572             08/08/2023 08:29:00 AM August 2023
200392 A886636             08/08/2023 03:30:00 PM August 2023
200393 A884257   Leo       06/30/2023 01:27:00 PM June 2023
200394 A886574             08/08/2023 08:29:00 AM August 2023
200395 A886388   Monkeyboy 08/04/2023 06:42:00 PM August 2023
200396 A884245   Bear      06/30/2023 12:32:00 PM June 2023
200397 A885910   Galaxy    07/27/2023 12:11:00 PM July 2023
200398 A886662   Mischief  08/09/2023 09:49:00 AM August 2023
200399 A886389   *Deepak   08/04/2023 08:06:00 PM August 2023
200400 A886649   886649    08/08/2023 06:52:00 PM August 2023
200401 A886665             08/09/2023 09:49:00 AM August 2023
200402 A886667             08/09/2023 09:49:00 AM August 2023
200403 A883852   *Percy    06/24/2023 03:00:00 PM June 2023
200404 A886631   *Franklin 08/08/2023 02:56:00 PM August 2023
200405 A882170   Osa       08/09/2023 12:02:00 PM August 2023
200406 A882170   Osa       08/09/2023 12:02:00 PM August 2023
200407 A886632   *Teddy    08/08/2023 02:56:00 PM August 2023
       found_location.x
1      Austin (TX)
2      Austin (TX)
3      E Riverside Dr/Royal Crest Dr in Austin (TX)
4      51St And Grover in Austin (TX)
5      Manor (TX)
6      12001 Metric Blvd in Austin (TX)
7      509 E Todd Lane in Austin (TX)
8      501 U.S. 183 in Austin (TX)
9      Abia in Austin (TX)
10     Payne in Austin (TX)
11     15043 Savannah Heights in Travis (TX)
12     4915 Yager Ln in Austin (TX)
13     1901 Onion Creek Pkwy in Austin (TX)
14     Austin (TX)
15     Austin (TX)
16     Austin (TX)
17     Austin (TX)
18     43 Rainey St in Austin (TX)
19     4708 Marblehead in Austin (TX)
20     23107 Fulkes Ln. in Austin (TX)
21     6808 Felipe Dr in Austin (TX)
22     Austin (TX)
23     Austin (TX)
24     111 E St Johns Ave in Austin (TX)
25     Travis (TX)
26     Austin (TX)
27     Montopolis/183 in Austin (TX)
28     2400 Wickersham in Austin (TX)
29     8224 Research Blvd #244 in Austin (TX)
30     Walsh Tarlton in Travis (TX)
⋮      ⋮
200378 1507 Darold Dr in Austin (TX)
200379 904 Fieldwood in Travis (TX)
200380 1020 Bird Creek in Austin (TX)
200381 Austin (TX)
200382 10705 Daryl Cove in Austin (TX)
200383 Rundberg Lane And Lamar Boulevard in Austin (TX)
200384 Fm 969 And Bantom Woods Road in Austin (TX)
200385 Austin (TX)
200386 Fm 969 And Bantom Woods Road in Austin (TX)
200387 12011 Yanez Drive in Travis (TX)
200388 1004 West Ave in Austin (TX)
200389 1004 West Ave in Austin (TX)
200390 1004 West Ave in Austin (TX)
200391 1004 West Ave in Austin (TX)
200392 Travis (TX)
200393 6907 Bitteroot Trl in Austin (TX)
200394 1004 West Ave in Austin (TX)
200395 2900 Sunridge Dr in Austin (TX)
200396 Austin (TX)
200397 Austin (TX)
200398 9000 Decker Ln Apt 246 in Travis (TX)
200399 Eva St And Johanna St in Austin (TX)
200400 Springdale in Austin (TX)
200401 9000 Decker Ln Apt 246 in Travis (TX)
200402 9000 Decker Ln Apt 246 in Travis (TX)
200403 Austin (TX)
200404 N Capital Of Texas Hwy And Plaza On The Lake in Austin (TX)
200405 Travis (TX)
200406 Travis (TX)
200407 N Capital Of Texas Hwy And Plaza On The Lake in Austin (TX)
       intake_type     intake_condition animal_type.x sex_upon_intake
1      Stray           Sick             Cat           Intact Female
2      Stray           Normal           Cat           Intact Female
3      Stray           Normal           Dog           Intact Male
4      Stray           Normal           Dog           Intact Male
5      Owner Surrender Normal           Dog           Spayed Female
6      Stray           Normal           Cat           Neutered Male
7      Stray           Normal           Dog           Intact Female
8      Stray           Normal           Cat           Intact Male
9      Stray           Normal           Cat           Unknown
10     Wildlife        Injured          Other         Unknown
11     Wildlife        Sick             Other         Unknown
12     Stray           Normal           Cat           Intact Male
13     Stray           Normal           Cat           Intact Female
14     Owner Surrender Normal           Cat           Intact Female
15     Owner Surrender Normal           Dog           Spayed Female
16     Owner Surrender Normal           Dog           Spayed Female
17     Stray           Normal           Dog           Intact Male
18     Wildlife        Normal           Other         Unknown
19     Stray           Normal           Dog           Spayed Female
20     Stray           Normal           Dog           Intact Male
21     Stray           Normal           Dog           Intact Female
22     Public Assist   Normal           Dog           Spayed Female
23     Public Assist   Normal           Dog           Spayed Female
24     Stray           Normal           Dog           Neutered Male
25     Owner Surrender Normal           Dog           Intact Male
26     Owner Surrender Normal           Cat           Intact Female
27     Stray           Normal           Dog           Intact Female
28     Stray           Normal           Dog           Intact Male
29     Stray           Normal           Cat           Intact Male
30     Stray           Normal           Dog           Intact Female
⋮      ⋮               ⋮                ⋮             ⋮
200378 Stray           Normal           Cat           Intact Female
200379 Stray           Normal           Cat           Intact Male
200380 Stray           Normal           Cat           Intact Female
200381 Owner Surrender Normal           Cat           Intact Female
200382 Stray           Normal           Cat           Intact Female
200383 Stray           Normal           Cat           Intact Female
200384 Stray           Normal           Cat           Intact Male
200385 Owner Surrender Normal           Cat           Spayed Female
200386 Stray           Normal           Cat           Intact Female
200387 Stray           Normal           Cat           Intact Female
200388 Stray           Neonatal         Cat           Intact Male
200389 Stray           Neonatal         Cat           Intact Male
200390 Stray           Neonatal         Cat           Intact Female
200391 Stray           Neonatal         Cat           Intact Female
200392 Owner Surrender Normal           Cat           Intact Male
200393 Stray           Normal           Cat           Intact Male
200394 Stray           Neonatal         Cat           Intact Male
200395 Stray           Normal           Cat           Intact Male
200396 Owner Surrender Normal           Dog           Intact Male
200397 Owner Surrender Sick             Cat           Intact Male
200398 Owner Surrender Normal           Cat           Intact Female
200399 Stray           Normal           Dog           Intact Male
200400 Stray           Normal           Cat           Intact Female
200401 Owner Surrender Normal           Cat           Intact Female
200402 Owner Surrender Normal           Cat           Intact Female
200403 Abandoned       Normal           Cat           Intact Male
200404 Stray           Normal           Cat           Intact Male
200405 Owner Surrender Injured          Dog           Spayed Female
200406 Owner Surrender Injured          Dog           Spayed Female
200407 Stray           Normal           Cat           Intact Male
       age_upon_intake ⋯ date_time.y            month_year.y date_of_birth
1      4 weeks         ⋯ 10/21/2013 11:39:00 AM Oct 2013     09/21/2013
2      1 month         ⋯ 12/20/2013 05:36:00 PM Dec 2013     09/16/2013
3      4 months        ⋯ 10/26/2013 06:32:00 PM Oct 2013     06/22/2013
4      10 years        ⋯ 10/25/2013 12:53:00 PM Oct 2013     02/21/2003
5      2 years         ⋯ 10/02/2013 12:40:00 PM Oct 2013     08/11/2011
6      3 years         ⋯ 10/22/2013 05:54:00 PM Oct 2013     04/18/2010
7      1 week          ⋯ 10/15/2013 02:33:00 PM Oct 2013     10/05/2013
8      1 month         ⋯ 12/18/2013 06:18:00 PM Dec 2013     08/18/2013
9      1 week          ⋯ 10/01/2013 10:39:00 AM Oct 2013     09/24/2013
10     0 years         ⋯ 10/26/2013 06:45:00 PM Oct 2013     10/26/2013
11     1 year          ⋯ 10/09/2013 03:59:00 PM Oct 2013     10/09/2012
12     1 weeks         ⋯ 10/01/2013 12:59:00 PM Oct 2013     09/22/2013
13     1 month         ⋯ 11/10/2013 04:56:00 PM Nov 2013     08/10/2013
14     3 months        ⋯ 11/10/2013 06:50:00 PM Nov 2013     07/23/2013
15     1 year          ⋯ 10/20/2013 04:29:00 PM Oct 2013     01/06/2012
16     1 year          ⋯ 05/12/2018 06:27:00 PM May 2018     01/06/2012
17     2 months        ⋯ 10/27/2013 04:30:00 PM Oct 2013     08/08/2013
18     1 year          ⋯ 10/21/2013 06:50:00 PM Oct 2013     10/21/2012
19     8 years         ⋯ 10/20/2013 03:10:00 PM Oct 2013     05/20/2005
20     1 year          ⋯ 03/04/2014 12:17:00 PM Mar 2014     04/03/2012
21     3 months        ⋯ 10/13/2013 07:06:00 PM Oct 2013     06/23/2013
22     1 year          ⋯ 07/23/2016 03:41:00 PM Jul 2016     04/24/2012
23     1 year          ⋯ 11/04/2013 03:00:00 PM Nov 2013     04/24/2012
24     2 years         ⋯ 10/27/2013 12:29:00 PM Oct 2013     08/01/2011
25     4 years         ⋯ 11/15/2013 06:13:00 PM Nov 2013     10/10/2008
26     1 month         ⋯ 11/10/2013 04:45:00 PM Nov 2013     08/19/2013
27     9 months        ⋯ 10/24/2013 04:54:00 PM Oct 2013     12/23/2012
28     8 years         ⋯ 10/28/2013 11:13:00 AM Oct 2013     10/23/2005
29     1 month         ⋯ 11/16/2013 05:09:00 PM Nov 2013     08/26/2013
30     4 years         ⋯ 10/11/2013 06:08:00 PM Oct 2013     10/08/2009
⋮      ⋮               ⋱ ⋮                      ⋮            ⋮
200378 1 month         ⋯ 08/12/2023 12:48:00 PM Aug 2023     04/27/2023
200379 1 month         ⋯ 08/08/2023 04:38:00 PM Aug 2023     04/26/2023
200380 4 months        ⋯ 09/07/2023 05:05:00 PM Sep 2023     03/24/2023
200381 2 months        ⋯ 08/08/2023 04:24:00 PM Aug 2023     04/06/2023
200382 1 month         ⋯ 08/08/2023 04:32:00 PM Aug 2023     05/28/2023
200383 3 months        ⋯ 08/22/2023 05:05:00 PM Aug 2023     05/04/2023
200384 2 months        ⋯ 08/08/2023 05:27:00 PM Aug 2023     05/22/2023
200385 8 months        ⋯ 08/13/2023 04:28:00 PM Aug 2023     11/08/2022
200386 2 months        ⋯ 08/08/2023 05:27:00 PM Aug 2023     05/22/2023
200387 1 year          ⋯ 08/08/2023 04:57:00 PM Aug 2023     05/30/2022
200388 2 weeks         ⋯ 08/08/2023 07:17:00 PM Aug 2023     07/20/2023
200389 2 weeks         ⋯ 08/08/2023 07:17:00 PM Aug 2023     07/20/2023
200390 2 weeks         ⋯ 08/08/2023 07:18:00 PM Aug 2023     07/20/2023
200391 2 weeks         ⋯ 08/08/2023 07:17:00 PM Aug 2023     07/20/2023
200392 5 months        ⋯ 08/16/2023 06:15:00 PM Aug 2023     03/08/2023
200393 1 month         ⋯ 08/08/2023 06:10:00 PM Aug 2023     04/30/2023
200394 2 weeks         ⋯ 08/08/2023 07:18:00 PM Aug 2023     07/20/2023
200395 1 year          ⋯ 08/16/2023 05:26:00 PM Aug 2023     07/21/2022
200396 3 years         ⋯ NA                     NA           NA
200397 5 months        ⋯ 08/26/2023 02:36:00 PM Aug 2023     02/20/2023
200398 2 years         ⋯ 08/22/2023 04:38:00 PM Aug 2023     08/09/2021
200399 2 years         ⋯ NA                     NA           NA
200400 2 weeks         ⋯ 08/09/2023 12:49:00 PM Aug 2023     07/24/2023
200401 3 months        ⋯ 08/17/2023 05:10:00 PM Aug 2023     05/09/2023
200402 3 months        ⋯ 08/17/2023 05:09:00 PM Aug 2023     05/09/2023
200403 10 months       ⋯ 08/26/2023 05:49:00 PM Aug 2023     08/09/2022
200404 1 month         ⋯ 09/13/2023 10:02:00 AM Sep 2023     06/28/2023
200405 9 months        ⋯ 08/15/2023 02:18:00 PM Aug 2023     11/01/2022
200406 9 months        ⋯ 07/06/2023 04:55:00 PM Jul 2023     11/01/2022
200407 1 month         ⋯ 09/11/2023 04:09:00 PM Sep 2023     06/28/2023
       outcome_type    outcome_subtype animal_type.y sex_upon_outcome
1      Transfer        Partner         Cat           Intact Female
2      Adoption        Foster          Cat           Spayed Female
3      Adoption                        Dog           Neutered Male
4      Return to Owner                 Dog           Intact Male
5      Adoption                        Dog           Spayed Female
6      Adoption                        Cat           Neutered Male
7      Transfer        Partner         Dog           Intact Female
8      Adoption                        Cat           Neutered Male
9      Transfer        Partner         Cat           Unknown
10     Euthanasia                      Other         Unknown
11     Euthanasia      Suffering       Other         Unknown
12     Transfer        Partner         Cat           Intact Male
13     Adoption                        Cat           Spayed Female
14     Transfer        Partner         Cat           Spayed Female
15     Transfer        Partner         Dog           Spayed Female
16     Return to Owner                 Dog           Spayed Female
17     Transfer        Partner         Dog           Neutered Male
18     Disposal                        Other         Unknown
19     Return to Owner                 Dog           Spayed Female
20     Adoption        Foster          Dog           Neutered Male
21     Adoption                        Dog           Spayed Female
22     Return to Owner                 Dog           Spayed Female
23     Return to Owner                 Dog           Spayed Female
24     Return to Owner                 Dog           Neutered Male
25     Transfer        Partner         Dog           Neutered Male
26     Adoption                        Cat           Spayed Female
27     Transfer        Partner         Dog           Intact Female
28     Return to Owner                 Dog           Neutered Male
29     Adoption                        Cat           Neutered Male
30     Return to Owner                 Dog           Spayed Female
⋮      ⋮               ⋮               ⋮             ⋮
200378 Adoption        Foster          Cat           Spayed Female
200379 Adoption                        Cat           Neutered Male
200380 Adoption                        Cat           Spayed Female
200381 Adoption                        Cat           Spayed Female
200382 Adoption                        Cat           Spayed Female
200383 Adoption        Foster          Cat           Spayed Female
200384 Adoption                        Cat           Neutered Male
200385 Adoption                        Cat           Spayed Female
200386 Adoption                        Cat           Spayed Female
200387 Adoption                        Cat           Spayed Female
200388 Transfer        Partner         Cat           Intact Male
200389 Transfer        Partner         Cat           Intact Male
200390 Transfer        Partner         Cat           Intact Female
200391 Transfer        Partner         Cat           Intact Female
200392 Adoption                        Cat           Neutered Male
200393 Adoption                        Cat           Neutered Male
200394 Transfer        Partner         Cat           Intact Male
200395 Adoption                        Cat           Neutered Male
200396 NA              NA              NA            NA
200397 Adoption        Foster          Cat           Neutered Male
200398 Adoption                        Cat           Spayed Female
200399 NA              NA              NA            NA
200400 Transfer        Partner         Cat           Intact Female
200401 Adoption        Foster          Cat           Spayed Female
200402 Adoption        Foster          Cat           Spayed Female
200403 Adoption                        Cat           Neutered Male
200404 Adoption        Foster          Cat           Neutered Male
200405 Transfer        Partner         Dog           Spayed Female
200406 Rto-Adopt                       Dog           Spayed Female
200407 Adoption        Foster          Cat           Neutered Male
       age_upon_outcome breed.y                            color.y
1      4 weeks          Domestic Shorthair Mix             Calico
2      3 months         Domestic Medium Hair Mix           Black
3      4 months         Cairn Terrier Mix                  Tan/White
4      10 years         Pit Bull                           Black
5      2 years          Norfolk Terrier Mix                Tan
6      3 years          Bengal                             Brown Tiger
7      1 weeks          Australian Cattle Dog Mix          Sable/White
8      4 months         Domestic Medium Hair Mix           Brown Tabby
9      1 week           Domestic Shorthair Mix             Orange/White
10     0 years          Squirrel Mix                       Gray/Brown
11     1 year           Raccoon Mix                        Brown/Black
12     1 weeks          Domestic Shorthair Mix             Orange Tabby
13     3 months         Domestic Shorthair Mix             Black
14     3 months         Domestic Shorthair Mix             Tortie
15     1 year           Pit Bull Mix                       Brown/White
16     6 years          Pit Bull Mix                       Brown/White
17     2 months         Chihuahua Shorthair Mix            White/Chocolate
18     1 year           Bat Mix                            Brown
19     8 years          Border Collie/Labrador Retriever   Chocolate/White

In [ ]:
# Finds each type of breed in Austin (TX)
merged_noempty %>%
  filter(found_location.x == "Austin (TX)") %>%
  count(breed.y, sort = TRUE)

     breed.y                                       n
1    Domestic Shorthair Mix                        7411
2    Pit Bull Mix                                  3434
3    Domestic Shorthair                            2994
4    Labrador Retriever Mix                        2445
5    Chihuahua Shorthair Mix                       1967
6    German Shepherd Mix                           1206
7    Pit Bull                                       745
8    Domestic Medium Hair Mix                       741
9    Australian Cattle Dog Mix                      551
10   German Shepherd                                461
11   Domestic Longhair Mix                          457
12   Labrador Retriever                             417
13   Chihuahua Shorthair                            400
14   Boxer Mix                                      360
15   Border Collie Mix                              338
16   Siamese Mix                                    335
17   Staffordshire Mix                              332
18   Dachshund Mix                                  307
19   Domestic Medium Hair                           296
20   Pointer Mix                                    277
21   Catahoula Mix                                  274
22   Australian Shepherd Mix                        251
23   Siberian Husky Mix                             236
24   Rat Terrier Mix                                232
25   Australian Kelpie Mix                          231
26   Beagle Mix                                     229
27   American Bulldog Mix                           224
28   Guinea Pig                                     224
29   Black Mouth Cur Mix                            223
30   Labrador Retriever/Pit Bull                    215
⋮    ⋮                                             ⋮
1411 Staffordshire/Chinese Sharpei                 1
1412 Staffordshire/Mastiff                         1
1413 Standard Poodle/Great Pyrenees                1
1414 Standard Schnauzer/Labrador Retriever         1
1415 Standard Schnauzer/Scottish Terrier           1
1416 Swiss Hound/Pit Bull                          1
1417 Tibetan Spaniel/Chihuahua Longhair            1
1418 Tonkinese                                     1
1419 Toy Fox Terrier                               1
1420 Toy Fox Terrier/Yorkshire Terrier             1
1421 Toy Poodle/Chihuahua Shorthair                1
1422 Toy Poodle/Cocker Spaniel                     1
1423 Toy Poodle/Yorkshire Terrier                  1
1424 Treeing Walker Coonhound                      1
1425 Turkish Angora                                1
1426 Vizsla/Catahoula                              1
1427 Vulture                                       1
1428 Weimaraner/American Bulldog                   1
1429 Welsh Terrier Mix                             1
1430 West Highland/Chihuahua Shorthair             1
1431 West Highland/Lhasa Apso                      1
1432 West Highland/Shetland Sheepdog               1
1433 West Highland/Soft Coated Wheaten Terrier     1
1434 Whippet                                       1
1435 Whippet/Treeing Cur                           1
1436 Wire Hair Fox Terrier/German Shepherd         1
1437 Wirehaired Vizsla Mix                         1
1438 Yorkshire Terrier/Chihuahua Longhair          1
1439 Yorkshire Terrier/Norfolk Terrier             1
1440 Yorkshire Terrier/Soft Coated Wheaten Terrier 1

In [ ]:
# Finds each type of breed in Del Valle (TX)
merged_noempty %>%
  filter(found_location.x == "Del Valle (TX)") %>%
  count(breed.y, sort = TRUE)

    breed.y                                             n
1   Domestic Shorthair Mix                              165
2   Pit Bull Mix                                         48
3   Labrador Retriever Mix                               41
4   Chihuahua Shorthair Mix                              35
5   German Shepherd Mix                                  33
6   Australian Cattle Dog Mix                            16
7   Cairn Terrier Mix                                    15
8   Australian Shepherd Mix                              14
9   Domestic Medium Hair Mix                             14
10  Catahoula Mix                                        11
11  Border Collie Mix                                    10
12  Labrador Retriever/Pit Bull                           9
13  Dachshund Wirehair/Miniature Poodle                   8
14  Dachshund/Chihuahua Shorthair                         8
15  Domestic Longhair Mix                                 8
16  Pit Bull                                              8
17  Soft Coated Wheaten Terrier Mix                       8
18  Anatol Shepherd/Great Pyrenees                        7
19  Bulldog Mix                                           7
20  Jack Russell Terrier Mix                              7
21  Pit Bull/German Shepherd                              7
22  Siberian Husky Mix                                    7
23  Labrador Retriever/German Shepherd                    6
24  Miniature Poodle Mix                                  6
25  Anatol Shepherd                                       5
26  Bearded Collie/Beagle                                 5
27  Dachshund Mix                                         5
28  Staffordshire Mix                                     5
29  Anatol Shepherd Mix                                   4
30  Plott Hound Mix                                       4
⋮   ⋮                                                   ⋮
100 German Shepherd/Doberman Pinsch                     1
101 German Shepherd/Labrador Retriever                  1
102 Golden Retriever Mix                                1
103 Great Dane/Mastiff                                  1
104 Great Pyrenees                                      1
105 Great Pyrenees Mix                                  1
106 Hamster                                             1
107 Hermit Crab Mix                                     1
108 Himalayan                                           1
109 Italian Greyhound Mix                               1
110 Jack Russell Terrier/Beagle                         1
111 Labrador Retriever/Australian Cattle Dog            1
112 Labrador Retriever/Boxer                            1
113 Labrador Retriever/Chow Chow                        1
114 Maine Coon Mix                                      1
115 Miniature Poodle/Bichon Frise                       1
116 Nova Scotia Duck Tolling Retriever/Golden Retriever 1
117 Papillon Mix                                        1
118 Pit Bull/Rat Terrier                                1
119 Rottweiler/Labrador Retriever                       1
120 Scottish Terrier/Basset Hound                       1
121 Shih Tzu Mix                                        1
122 Siberian Husky                                      1
123 Siberian Husky/Australian Cattle Dog                1
124 Soft Coated Wheaten Terrier                         1
125 Soft Coated Wheaten Terrier/Labrador Retriever      1
126 St. Bernard Smooth Coat                             1
127 Toy Poodle Mix                                      1
128 Whippet Mix                                         1
129 Yorkshire Terrier/Miniature Schnauzer               1

In [ ]:
# Finds each type of breed in Manor (TX)
merged_noempty %>%
  filter(found_location.x == "Manor (TX)") %>%
  count(breed.y, sort = TRUE)

    breed.y                                n
1   Domestic Shorthair Mix                 178
2   Labrador Retriever Mix                  97
3   Pit Bull Mix                            96
4   German Shepherd Mix                     40
5   Domestic Shorthair                      39
6   Chihuahua Shorthair Mix                 37
7   Pit Bull                                27
8   German Shepherd                         23
9   Domestic Medium Hair Mix                18
10  Domestic Longhair Mix                   15
11  Beagle Mix                              13
12  Chihuahua Shorthair                     13
13  Labrador Retriever                      12
14  Australian Cattle Dog Mix               11
15  Dachshund Mix                           10
16  Great Pyrenees Mix                      10
17  Rabbit Sh                               10
18  Cairn Terrier Mix                        9
19  Anatol Shepherd Mix                      8
20  Staffordshire Mix                        8
21  American Pit Bull Terrier Mix            7
22  Anatol Shepherd                          7
23  Australian Cattle Dog/Belgian Malinois   7
24  Australian Shepherd Mix                  7
25  Black Mouth Cur Mix                      7
26  Border Collie Mix                        7
27  Golden Retriever Mix                     7
28  Miniature Schnauzer                      7
29  Catahoula Mix                            6
30  Dachshund/Plott Hound                    6
⋮   ⋮                                      ⋮
129 Dachshund Longhair/Cocker Spaniel      1
130 Doberman Pinsch/Greyhound              1
131 Flemish Giant Mix                      1
132 German Shepherd/Anatol Shepherd        1
133 German Shepherd/Australian Shepherd    1
134 German Shepherd/Border Collie          1
135 German Shepherd/Great Pyrenees         1
136 German Shepherd/Siberian Husky         1
137 German Shorthair Pointer               1
138 Jack Russell Terrier                   1
139 Labrador Retriever/Boxer               1
140 Labrador Retriever/Golden Retriever    1
141 Labrador Retriever/Queensland Heeler   1
142 Labrador Retriever/Standard Poodle     1
143 Maine Coon Mix                         1
144 Maltese/Miniature Poodle               1
145 Miniature Schnauzer/Miniature Poodle   1
146 Munchkin Longhair Mix                  1
147 Norfolk Terrier Mix                    1
148 Parson Russell Terrier                 1
149 Pbgv Mix                               1
150 Pit Bull/Labrador Retriever            1
151 Pomeranian                             1
152 Pomeranian Mix                         1
153 Rat Terrier                            1
154 Rottweiler/Labrador Retriever          1
155 Soft Coated Wheaten Terrier            1
156 St. Bernard Rough Coat/Beagle          1
157 Toy Poodle Mix                         1
158 Yorkshire Terrier/Maltese              1

In [ ]:
# Finds each type of breed in Pfugerville (TX)
merged_noempty %>%
  filter(found_location.x == "Pflugerville (TX)") %>%
  count(breed.y, sort = TRUE)

    breed.y                                  n
1   Domestic Shorthair Mix                   174
2   Pit Bull Mix                              84
3   Labrador Retriever Mix                    80
4   Domestic Shorthair                        46
5   Chihuahua Shorthair Mix                   34
6   Domestic Medium Hair Mix                  31
7   German Shepherd Mix                       23
8   Australian Cattle Dog Mix                 21
9   Anatol Shepherd Mix                       19
10  Labrador Retriever/German Shepherd        19
11  Labrador Retriever                        15
12  Staffordshire Mix                         15
13  German Shepherd                           13
14  Dachshund Mix                             12
15  Domestic Longhair Mix                     12
16  Siberian Husky Mix                        12
17  American Bulldog Mix                      10
18  Boxer Mix                                 10
19  Catahoula Mix                             10
20  Black/Tan Hound Mix                        9
21  Cairn Terrier Mix                          9
22  Dachshund                                  9
23  Bull Terrier Mix                           8
24  Chihuahua Shorthair                        8
25  Pointer Mix                                8
26  Australian Cattle Dog/Belgian Malinois     7
27  Australian Shepherd Mix                    7
28  Belgian Malinois                           7
29  Labrador Retriever/Rottweiler              7
30  Landseer Mix                               7
⋮   ⋮                                        ⋮
150 Jack Russell Terrier/Chihuahua Shorthair 1
151 Jack Russell Terrier/Manchester Terrier  1
152 Labrador Retriever/Basset Hound          1
153 Maltese                                  1
154 Maltese/Miniature Poodle                 1
155 Manx Mix                                 1
156 Miniature Pinscher/Whippet               1
157 Miniature Poodle Mix                     1
158 Miniature Poodle/Cocker Spaniel          1
159 Miniature Poodle/Yorkshire Terrier       1
160 Miniature Schnauzer Mix                  1
161 Netherlnd Dwarf Mix                      1
162 Pekingese Mix                            1
163 Pit Bull/Beagle                          1
164 Pit Bull/Belgian Malinois                1
165 Pit Bull/Dalmatian                       1
166 Pit Bull/Mastiff                         1
167 Plott Hound                              1
168 Pointer/Pit Bull                         1
169 Pomeranian                               1
170 Pug/Beagle                               1
171 Rabbit Sh Mix                            1
172 Rhod Ridgeback Mix                       1
173 Rottweiler                               1
174 Siberian Husky                           1
175 Standard Schnauzer                       1
176 Toy Poodle                               1
177 Vizsla Mix                               1
178 Wire Hair Fox Terrier Mix                1
179 Yorkshire Terrier Mix                    1

In [ ]:
# Finds each type of breed in Travis (TX)
merged_noempty %>%
  filter(found_location.x == "Travis (TX)") %>%
  count(breed.y, sort = TRUE)

    breed.y                                  n
1   Domestic Shorthair Mix                   491
2   Domestic Shorthair                       456
3   Labrador Retriever Mix                   296
4   Pit Bull Mix                             277
5   Chihuahua Shorthair Mix                  175
6   German Shepherd Mix                      125
7   Pit Bull                                 111
8   German Shepherd                           91
9   Labrador Retriever                        86
10  Australian Cattle Dog Mix                 80
11  Domestic Medium Hair                      55
12  Chihuahua Shorthair                       52
13  Anatol Shepherd Mix                       46
14  Boxer Mix                                 41
15  Catahoula Mix                             37
16  Domestic Medium Hair Mix                  36
17  Border Collie Mix                         33
18  Australian Cattle Dog                     30
19  Great Pyrenees Mix                        30
20  Guinea Pig                                28
21  Labrador Retriever/German Shepherd        28
22  Rottweiler Mix                            26
23  Maltese                                   25
24  Jack Russell Terrier Mix                  24
25  Siamese Mix                               24
26  Chihuahua Shorthair/Dachshund             22
27  Siberian Husky                            22
28  Staffordshire Mix                         22
29  Australian Shepherd Mix                   21
30  Siamese                                   21
⋮   ⋮                                        ⋮
383 Rat Terrier/Chihuahua Shorthair          1
384 Redbone Hound                            1
385 Rottweiler/German Shepherd               1
386 Shetland Sheepdog                        1
387 Shih Tzu                                 1
388 Shih Tzu/Chihuahua Longhair              1
389 Shih Tzu/Havanese                        1
390 Shih Tzu/Maltese                         1
391 Silky Terrier Mix                        1
392 Smooth Fox Terrier                       1
393 Smooth Fox Terrier/Chihuahua Shorthair   1
394 Snake Mix                                1
395 Snowshoe                                 1
396 Squirrel Mix                             1
397 Staffordshire/Dachshund                  1
398 Standard Poodle/Labrador Retriever       1
399 Tortoise                                 1
400 Toy Poodle/Maltese                       1
401 Toy Poodle/Yorkshire Terrier             1
402 Treeing Tennesse Brindle Mix             1
403 Treeing Walker Coonhound Mix             1
404 Vizsla                                   1
405 Weimaraner Mix                           1
406 West Highland                            1
407 West Highland Mix                        1
408 Whippet/Australian Kelpie                1
409 Whippet/Beagle                           1
410 Whippet/Catahoula                        1
411 Whippet/English Pointer                  1
412 Wire Hair Fox Terrier/Chihuahua Longhair 1

In [ ]:
# Finds each type of breed in Cedar Park (TX)
merged_noempty %>%
  filter(found_location.x == "Cedar Park (TX)") %>%
  count(breed.y, sort = TRUE)

   breed.y                               n
1  Domestic Shorthair Mix                21
2  Pit Bull Mix                          18
3  German Shepherd Mix                   17
4  Labrador Retriever Mix                10
5  Australian Cattle Dog Mix              8
6  Chihuahua Shorthair Mix                8
7  Domestic Shorthair                     8
8  Jack Russell Terrier Mix               6
9  Pit Bull/Catahoula                     5
10 Anatol Shepherd Mix                    4
11 Border Collie/Beagle                   4
12 Staffordshire Mix                      4
13 Black Mouth Cur Mix                    3
14 Catahoula Mix                          3
15 Domestic Medium Hair                   3
16 Great Dane Mix                         3
17 Great Pyrenees Mix                     3
18 Guinea Pig Mix                         3
19 Labrador Retriever/Great Pyrenees      3
20 Miniature Poodle Mix                   3
21 Miniature Schnauzer Mix                3
22 Queensland Heeler Mix                  3
23 Whippet/Beagle                         3
24 Australian Cattle Dog/German Shepherd  2
25 Basenji Mix                            2
26 Bloodhound Mix                         2
27 Blue Lacy Mix                          2
28 Boxer Mix                              2
29 Catahoula/Labrador Retriever           2
30 Chihuahua Shorthair/Rat Terrier        2
31 Chow Chow                              2
32 Chow Chow Mix                          2
33 Dachshund/Pug                          2
34 Domestic Medium Hair Mix               2
35 Labrador Retriever/Pit Bull            2
36 Lionhead                               2
37 Pointer Mix                            2
38 Siamese Mix                            2
39 Airedale Terrier Mix                   1
40 Cairn Terrier Mix                      1
41 English Bulldog Mix                    1
42 Labrador Retriever                     1
43 Labrador Retriever/Weimaraner          1
44 Shih Tzu Mix                           1
45 Staffordshire                          1